### ISSUE TITLE
Errors due to JFreeChart and JCommon Libraries

### ISSUE THREAD

**Issue by Sayune** [NathanDarpentigny/Deep-learning-GLAdOS#1]
The default locations for theses two libraries are : 
-C:/Users/Laty/Downloads/JFreeChart1.0.19 
-C:/Users/Laty/Downloads/JCommon1.0.23
So the class "LearningWindow" will obviously work only on Latylus PC . 
I was able to run the code on my PC by downloading those two libraries and changing the build path of the Java project to the correct path on my own PC. However, this solution is not pratictal as it requires for every member to change the Build path of those libraries after each pull from the repo. I suggest that we add the libraries to the repo (on the master branch) and change the Build path to local files on the project so that the code runs on every PC.
I have never used JFreeChart and Jcommon Libraries so i'm not sure if there is a better solution to fix this issue. What do u think about it guys ?

**Comment by Latylus** [comment]
The issued has been solved with the latest commit, as soon as you pull everything should work. If it doesn't, contact me again.
